OpenHomesDisplayInWeb/Models/DataBase.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace OpenHomesDisplayInWeb
{
    class SaveToDB
    {
        public void Insert(List<Region> regions)
        {
            //OpenHomeDBContext db = new OpenHomeDBContext();
            using (OpenHomeDBContext db = new OpenHomeDBContext())
            {
                var regionListFromDB = db.RegionModels.ToList();
                if (regionListFromDB.Count > 0)
                {
                    foreach (var item in regionListFromDB)
                    {
                        db.RegionModels.Remove(item);
                        db.SaveChanges();
                    }
                }

                foreach (Region region in regions)
                {
                    db.RegionModels.Add(region);
                    db.SaveChanges();
                }
            }
        }
    }

    class GetData
    {
        public void GetDataFromDB()
        {
            using (OpenHomeDBContext db = new OpenHomeDBContext())
            {
                var suburbListFromDB = db.SuburbModels.ToList();
                Console.WriteLine("------------------");
                Console.WriteLine("------------------");
                Console.WriteLine("FROM DB");

                foreach (var suburb in suburbListFromDB)
                {
                    Console.WriteLine(suburb.SuburbName);
                    Console.WriteLine("------------------");
                    var homesListFromDB = db.OpenHomeModels.Where(s => s.Suburb.SuburbName == suburb.SuburbName).ToList();
                    int homeCount = 0;
                    foreach (var home in homesListFromDB)
                    {
                        Console.WriteLine();
                        Console.WriteLine("Home " + ++homeCount);
                        Console.WriteLine("Location = " + home.Location);
                        Console.WriteLine("Rooms = " + home.Rooms);
                        Console.WriteLine("Property Type = " + home.PropertyType);
                        Console.WriteLine("Price = " + home.Price);
                        Console.WriteLine("Parking = " + home.Parking);
                        Console.WriteLine("Open Home Time = " + home.OpenHomeTime);
                        Console.WriteLine();
                    }
                }
            }
        }
    }
}

OpenHomesDisplayInWeb/Models/OpenHomeDBContext.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace OpenHomesDisplayInWeb
{
    class OpenHomeDBContext : DbContext
    {
        public DbSet<OpenHome> OpenHomeModels { get; set; }
        public DbSet<Suburb> SuburbModels { get; set; }
        public DbSet<District> DistrictModels { get; set; }
        public DbSet<Region> RegionModels { get; set; }
    }
}

OpenHomesDisplayInWeb/Models/OpenHomeDBModels.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace OpenHomesDisplayInWeb
{
    public class RegionsClass
    {
        public static List<Region> RegionsList { get; set; }
    }

    public class Region
    {
        [Key]
        public int Id { get; set; }
        public string RegionName { get; set; }
        public List<District> DistrictList { get; set; }
    }

    public class District
    {
        [Key]
        public int Id { get; set; }
        public string DistrictName { get; set; }
        public List<Suburb> SuburbList { get; set; }
        public int RegionId { get; set; }
        [ForeignKey("RegionId")]
        public virtual Region Region { get; set; }
    }

    public class Suburb
    {
        [Key]
        public int Id { get; set; }
        public string SuburbName { get; set; }
        public virtual List<OpenHome> HomeList { get; set; }
        public int DistrictId { get; set; }
        [ForeignKey("DistrictId")]
        public virtual District District { get; set; }
    }

    public class OpenHome
    {
        [Key]
        public int Sl_No { get; set; }
        public string Location { get; set; }
        public string Rooms { get; set; }
        public string PropertyType { get; set; }
        public string Price { get; set; }
        public string Parking { get; set; }
        public string OpenHomeTime { get; set; }
        public int SuburbId { get; set; }
        [ForeignKey("SuburbId")]
        public virtual Suburb Suburb { get; set; }
    }
}

OpenHomesDisplayInWeb/Controllers/ResultController.cs
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using Newtonsoft.Json;
using Formatting = Newtonsoft.Json.Formatting;

namespace OpenHomesDisplayInWeb.Controllers
{
    public class ResultController : Controller
    {
        OpenHomeDBContext db = new OpenHomeDBContext();

        public ActionResult Home()
        {
            return View();
        }


        public ActionResult Index(string name)
        {
            //List<Suburb> suburb = db.SuburbModels.Where(s => s.SuburbName == name).ToList();
            //ViewBag.Suburb = suburb;
            //Homes homes = new Homes();
            return View();

        }

        public JsonResult GetHomeDetails(string region, string district, string suburb)
        {
            var result = Homes.HomesMain(region, district, suburb);
            return Json(result.HomeList, JsonRequestBehavior.AllowGet);
            /*List<Suburb> suburbs = db.SuburbModels.Where(s => s.SuburbName == name).ToList();
            var homeList = db.OpenHomeModels.Where(s => s.Suburb.SuburbName == name).Select(x => new
            {
                Location = x.Location,
                Rooms = x.Rooms,
                PropertyType = x.PropertyType,
                Price = x.Price,
                Parking = x.Parking,
                OpenHomeTime = x.OpenHomeTime
            });
            return Json(homeList, JsonRequestBehavior.AllowGet);*/
        }

        public JsonResult NewRegions()
        {
            if (!RouteConfig.browserOpen)
            {
                Program.Main();
                RouteConfig.browserOpen = true;
            }
            var regions = TradeMe.regionsList;
            string value = string.Empty;
            value = JsonConvert.SerializeObject(regions, Formatting.Indented, new JsonSerializerSettings
            {
                ReferenceLoopHandling = ReferenceLoopHandling.Ignore
            });

            return Json(value, JsonRequestBehavior.AllowGet);
        }

        public JsonResult Regions()
        {
            if (!RouteConfig.browserOpen)
            {
                Program.Main();
                RouteConfig.browserOpen = true;
            }
            var regions = db.RegionModels.ToList();
            foreach (var region in regions)
            {
                List<District> distList = db.DistrictModels.Where(r => r.Region.RegionName == region.RegionName).ToList();

                //distList = db.DistrictModels.Where(r => r.Region.RegionName == region.RegionName).ToList();
                foreach (var district in distList)
                {
                    List<Suburb> suburbList = db.SuburbModels.Where(d => d.District.DistrictName == district.DistrictName).ToList();
                    //suburbList = db.SuburbModels.Where(d => d.District.DistrictName == district.DistrictName).ToList();
                }
            }
            string value = string.Empty;
            value = JsonConvert.SerializeObject(regions, Formatting.Indented, new JsonSerializerSettings
            {
                ReferenceLoopHandling = ReferenceLoopHandling.Ignore
            });

            return Json(value, JsonRequestBehavior.AllowGet);
        }

    }
}

OpenHomesDisplayInWeb/Views/Result/Home.cshtml
@{
    ViewBag.Title = "Home";
}

<h2>Suburb selection</h2>

<p data-bind="text: Search, visible: SearchStatus" style="color:red"></p>

<div class="container">
    <div>
        <div data-bind="visible: SearchRegions">
            <label class="control-label col-sm-3">Region Name</label>
            <select class="form-control col-sm-9" data-bind="options: regions,
                                                             optionsText: 'RegionName',
                                                             value: selectedRegion,
                                                             optionsCaption: '--Select Region--'"></select>
        </div>
        <br />
        <br />
        <div data-bind="with: selectedRegion">
            <div class="form-group">
                <label class="control-label col-sm-3">District Name</label>

                <select class="form-control col-sm-9" data-bind="options: DistrictList,
                                                             optionsText: 'DistrictName',
                                                             value: selectedDistrict,
                                                             optionsCaption: '--Select District--'"></select>
            </div>
        </div>
        <br />
        <br />
        <div data-bind="with: selectedDistrict">
            <div class="form-group">
                <label class="control-label col-sm-3">Suburb Name</label>
                <select class="form-control col-sm-8" data-bind="options: SuburbList,
                        optionsText: 'SuburbName',
                        value: selectedSuburb,
                        optionsCaption: '--Select Suburb--'"></select>
            </div>
            <button class="form-group col-sm-offset-1 btn btn-default" data-bind="click: searchSuburb">Search</button>
        </div>
    </div>
</div>
<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/knockout-3.4.2.js"></script>
<script src="~/Scripts/suburb.js"></script>

OpenHomesDisplayInWeb/Views/Result/Index.cshtml
<link href="~/Content/bootstrap.min.css" rel="stylesheet" />
<div class="container">
    <h2>Homes</h2>

    @*@foreach (var suburb in ViewBag.Suburb)
    {
        <h4>@suburb.SuburbName</h4>
        if (suburb.HomeList.Count > 0)
        {
            int homeCount = 0;
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th>Sl.No</th>
                        <th>Location</th>
                        <th>Room</th>
                        <th>Property type</th>
                        <th>Price</th>
                        <th>Parking</th>
                        <th>Open home time</th>
                    </tr>
                </thead>

                @foreach (var home in suburb.HomeList)
                {
                    homeCount++;
                    <tbody>
                        <tr>
                            <td>@homeCount</td>
                            <td>@home.Location</td>
                            <td>@home.Rooms</td>
                            <td>@home.PropertyType</td>
                            <td>@home.Price</td>
                            <td>@home.Parking</td>
                            <td>@home.OpenHomeTime</td>
                        </tr>
                    </tbody>
                }
            </table>
        }
        else
        {
            <p>No homes to display</p>
        }
    }*@



    <table class="table table-striped navbar-static-top" id="wrap">
            <thead>
                <tr>
                    <th>Sl.No</th>
                    <th>Location</th>
                    <th>Room</th>
                    <th>Property type</th>
                    <th>Price</th>
                    <th>Parking</th>
                    <th>Open home time</th>
                </tr>
            </thead>
            <tbody>
                <tr data-bind="text: Search, visible: SearchStatus" style="color:red"></tr>
            </tbody>
            <tbody data-bind="foreach: home">
                <tr>
                    <td data-bind="text: $index() + 1"></td>
                    <td data-bind="text: Location"></td>
                    <td data-bind="text: Rooms"></td>
                    <td data-bind="text: PropertyType"></td>
                    <td data-bind="text: Price"></td>
                    <td data-bind="text: Parking"></td>
                    <td data-bind="text: OpenHomeTime"></td>
                </tr>
            </tbody>
        </table>


    <br />
</div>

<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/knockout-3.4.2.js"></script>
<script src="~/Scripts/homes.js"></script>

OpenHomesDisplayInWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Open homes</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Open homes", "Home", "Result", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>